map $http_origin $cors_origin {
    "https://lex-admin.0w0.my"  "https://lex-admin.0w0.my";
    "http://localhost:5180"      "http://localhost:5180";
    "http://localhost:5173"      "http://localhost:5173";
    default                      "";
}
